print("GOD BOTHERER by Health")
print("I wake up in the dark of night (Tell me how does it feel?)")
print("Do you ever think about me? (Do I need to be?)")
print("You're sleeping alone tonight (Tonight, right here)")
print("How does it feel, what do you think?")
print("Are you happy?\n")

print("Faith in everything")
print("Faith in all you need")
print("Faith in everything")
print("Now")
print("Pain in everything you know\n")

print("I wake up with the stars at night")
print("Tell me what you feel")
print("And I cannot feel you by me")
print("It didn't need to be")
print("You sleep alone tonight (Glory and I hear)")
print("How does it feel, what do you think?")
print("Do you still hate me?")
